services:
  db:
    image: postgres:alpine
    container_name: final-db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  fastapi:
    build: https://github.com/Dereto/wap-final-be.git
    container_name: final-be
    env_file:
      - ./.env
    depends_on:
      - db
      - node

  node:
    build: https://github.com/Dereto/wap-final-fs.git
    container_name: final-fs
    environment:
      - PORT=3000

  nginx:
    image: nginx:alpine
    container_name: final-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
      - node